stages:
  - build
  - deploy

build:
  stage: build
  image: alpine
  script:
    - echo "required files are teested for pipeline"


deploy:
  stage: deploy
  image: alpine
  before_script:
    - mkdir -p ~/testAWS
    - cd ~/testAWS
    - echo "Hello sample file deployed via ssh from gitlab runner" >> service.txt
    - echo "bGljZW5jZSBmaWxlIGZvciBlYzI=" >> licence.txt
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - cd ~/testAWS
    - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no service.txt ubuntu@ec2-54-151-33-56.us-west-1.compute.amazonaws.com:/home/ubuntu
    - scp -o StrictHostKeyChecking=no licence.txt ubuntu@ec2-54-151-33-56.us-west-1.compute.amazonaws.com:/home/ubuntu
    - echo "file transfered to EC2 instance on aws"

