
-- the table assest queries
SELECT M.ID,M.CUST_NAME, L.ORDERQUANT
>    FROM CUST M
>    INNER JOIN ORDERS  L
>    ON M.ROWKEY = L.ROWKEY
>    EMIT CHANGES
>    LIMIT 3;


-- ASSIGN AND CREATE A NEW TOPIC FROM PARTITION CONSUMED;
CREATE TABLE USERS_QUANTITY AS SELECT M.ID,M.CUST_NAME, L.ORDERQUANT
>    FROM CUST M
>    INNER JOIN ORDERS  L
>    ON M.ROWKEY = L.ROWKEY
>    EMIT CHANGES
>    LIMIT 3;


-- time assets queries
CREATE STREAM REQUESTFILECOUNT(startime STRING,filename STRING,timestamp VARCHAR) WITH(KAFKA
_TOPIC='userfiles',TIMESTAMP='timestamp',TIMESTAMP_FORMAT='yyyy-MM-dd''T''HH:mm:ssX',VALUE_FORMAT=
'Avro',PARTITIONS=1);


SELECT * FROM CUST EMIT CHANGES 


-- limit asset topic queries
PRINT USERS_QUANTITY FROM BEGINNING LIMIT 3;

CREATE TABLE CUST(ID BIGINT,CUST_NAME VARCHAR) WITH (kafka_topic='customer',partitions=1,value_format='avro')
CREATE TABLE Orders(ID BIGINT,CUST_NAME VARCHAR) WITH (kafka_topic='customer',partitions=1,value_format='avro')




-- windowed tumbling aggregate
create STREAM user(username STRING,filename STRING,filecount BIGINT,ACCENTUATE VARCHAR) WITH(kafka_topic='files',value_format='json',timestamp='ACCENTUATE',timestamp_format='yyyy-MM-dd HH:mm:ss');

insert into user(ROWKEY,USERNAME,FILENAME,FILECOUNT,ACCENTUATE) VALUES('1','DANIEL','AA',1,'2021-01-29 01:00:00')
insert into user(ROWKEY,USERNAME,FILENAME,FILECOUNT,ACCENTUATE) VALUES('2','DAVID','AA',1,'2021-01-29 01:00:01');
insert into user(ROWKEY,USERNAME,FILENAME,FILECOUNT,ACCENTUATE) VALUES('2','DANIEL','AA',1,'2021-01-29 01:00:03');
insert into user(ROWKEY,USERNAME,FILENAME,FILECOUNT,ACCENTUATE) VALUES('3','DANIEL','AA',2,'2021-01-29 01:00:03');
insert into user(ROWKEY,USERNAME,FILENAME,FILECOUNT,ACCENTUATE) VALUES('4','MATT','AA',2,'2021-01-29 01:00:04');
insert into user(ROWKEY,USERNAME,FILENAME,FILECOUNT,ACCENTUATE) VALUES('5','DANIEL','AA',2,'2021-01-29 01:00:04');


select USERNAME,COUNT(*) AS FILEcOUNTS,WINDOWSTART AS WS,WINDOWEND AS WE FROM USER WINDOW TUMBLING (SIZE 10 MINUTE) GROUP BY ROWKEY EMIT CHANGES LIMIT 5;
-- PERSISTANT TABLE RUN BACKGROUND QUEROES;

CREATE TABLE WINDOWTUMBLING WITH(kafka_topic='files') AS select USERNAME,COUNT(*) AS FILEcOUNTS,WINDOWSTART AS WS,WINDOWEND AS WE FROM USER WINDOW TUMBLING (SIZE 10 MINUTE) GROUP BY USERNAME  EMIT CHANGES LIMIT 5;
CREATE TABLE HOPPINGFILES AS
  select USERNAME,COUNT(*) AS FILEcOUNTS,WINDOWSTART AS WS,WINDOWEND AS WE FROM USER 
  WINDOW HOPPING (SIZE 30 SECONDS, ADVANCE BY 10 SECONDS, RETENTION 7 DAYS, GRACE PERIOD 30 MINUTES)
  GROUP BY USERNAME
  EMIT CHANGES;